<?php
declare(strict_types=1);require dirname(__DIR__).'/bootstrap.php';use App\Core\Database;
$pass=$fail=$skip=0;function result(string$name,string$status,string$detail=''):void{global$pass,$fail,$skip;${$status}++;echo'['.strtoupper($status).'] '.$name.($detail?' — '.$detail:'').PHP_EOL;}function test(string$name,callable$fn):void{try{$x=$fn();if($x===null)result($name,'skip','required seed data unavailable');elseif($x===true)result($name,'pass');else result($name,'fail',(string)$x);}catch(Throwable$e){result($name,'fail',$e->getMessage());}}
try{$pdo=Database::connection();result('Database connection','pass');}catch(Throwable$e){result('Database connection','fail',$e->getMessage());exit(1);}
$tables=['users','roles','appointments','doctor_schedules','ai_knowledge_base','symptoms','career_jobs','job_applications','campus_ambassador_applications','affiliates','affiliate_referrals','affiliate_commissions'];
test('Phase 1–6 database tables',function()use($pdo,$tables){$s=$pdo->prepare('SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name=?');foreach($tables as$t){$s->execute([$t]);if(!(int)$s->fetchColumn())return'Missing table: '.$t;}return true;});
test('Appointment conflict unique index',function()use($pdo){$s=$pdo->query("SHOW INDEX FROM appointments WHERE Key_name='uq_doctor_active_datetime'");return count($s->fetchAll())>0?:'Conflict-prevention index is missing.';});
test('Appointment duplicate booking rejection',function()use($pdo){$row=$pdo->query("SELECT u.id patient_id,d.id doctor_id,dd.department_id,d.consultation_fee FROM users u JOIN user_roles ur ON ur.user_id=u.id JOIN roles r ON r.id=ur.role_id AND r.name='patient' CROSS JOIN doctors d JOIN doctor_departments dd ON dd.doctor_id=d.id WHERE u.is_active=1 AND d.is_active=1 LIMIT 1")->fetch();if(!$row)return null;$date=date('Y-m-d',strtotime('+370 days'));$time='06:01:00';$pdo->beginTransaction();try{$sql="INSERT INTO appointments(appointment_number,patient_id,doctor_id,department_id,appointment_date,appointment_time,reason,consultation_fee,status)VALUES(?,?,?,?,?,?,?,?,'pending')";$s=$pdo->prepare($sql);$s->execute(['QA-'.bin2hex(random_bytes(5)),$row['patient_id'],$row['doctor_id'],$row['department_id'],$date,$time,'Automated conflict test',$row['consultation_fee']]);try{$s->execute(['QA-'.bin2hex(random_bytes(5)),$row['patient_id'],$row['doctor_id'],$row['department_id'],$date,$time,'Automated duplicate test',$row['consultation_fee']]);return'Duplicate active slot was accepted.';}catch(PDOException$e){return$e->getCode()==='23000';}}finally{if($pdo->inTransaction())$pdo->rollBack();}});
test('Administrator business and AI permissions',function()use($pdo){$needed=['careers.manage','ambassadors.manage','affiliates.manage','ai.manage','ai.reports'];$s=$pdo->prepare("SELECT COUNT(*) FROM role_permissions rp JOIN roles r ON r.id=rp.role_id JOIN permissions p ON p.id=rp.permission_id WHERE r.name='admin' AND p.name=?");foreach($needed as$p){$s->execute([$p]);if(!(int)$s->fetchColumn())return'Missing admin permission: '.$p;}return true;});
test('Patients do not receive admin permissions',function()use($pdo){return!(int)$pdo->query("SELECT COUNT(*) FROM role_permissions rp JOIN roles r ON r.id=rp.role_id JOIN permissions p ON p.id=rp.permission_id WHERE r.name='patient' AND p.name IN('careers.manage','ambassadors.manage','affiliates.manage','ai.manage')")->fetchColumn()?:'Patient role has an administrator permission.';});
test('Résumé storage is outside public web root',fn()=>str_starts_with(realpath(BASE_PATH.'/storage')?:'',realpath(BASE_PATH)?:'')&&!str_starts_with(realpath(BASE_PATH.'/storage')?:'',realpath(BASE_PATH.'/public')?:'')?:'Storage path is unsafe.');
test('Upload execution protection',fn()=>is_file(BASE_PATH.'/public/uploads/.htaccess')&&str_contains(file_get_contents(BASE_PATH.'/public/uploads/.htaccess'),'Require all denied')?:'Upload .htaccess protection is missing.');
test('Emergency symptom rules exist',function()use($pdo){$n=(int)$pdo->query("SELECT COUNT(*) FROM symptoms WHERE is_active=1 AND is_emergency=1 AND emergency_message_en IS NOT NULL")->fetchColumn();return$n>=4?:'Expected at least four active emergency rules.';});
test('Bengali AI knowledge exists',function()use($pdo){return(int)$pdo->query("SELECT COUNT(*) FROM ai_knowledge_base WHERE is_active=1 AND answer_bn IS NOT NULL AND answer_bn<>''")->fetchColumn()>0?:'No Bengali knowledge answers found.';});
test('Emergency intent precedes other assistant intents',function(){$code=file_get_contents(BASE_PATH.'/app/Models/AiAssistant.php');$e=strpos($code,'self::emergency');$s=strpos($code,'self::symptom');return$e!==false&&$s!==false&&$e<$s?:'Emergency evaluation is not first.';});
test('CSRF enforcement for every POST route',function(){$code=file_get_contents(BASE_PATH.'/app/Core/Router.php');return str_contains($code,"method()==='POST'")&&str_contains($code,'Csrf::verify')?:'Router-level CSRF enforcement not found.';});
test('Production security headers configured',function(){$h=file_get_contents(BASE_PATH.'/public/.htaccess');foreach(['Content-Security-Policy','X-Content-Type-Options','X-Frame-Options','Referrer-Policy']as$x)if(!str_contains($h,$x))return'Missing '.$x;return true;});
echo PHP_EOL."Summary: {$pass} passed, {$fail} failed, {$skip} skipped".PHP_EOL;exit($fail?1:0);
