USE advance_care_hospital;

CREATE TABLE career_jobs(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(180) NOT NULL,slug VARCHAR(190) NOT NULL UNIQUE,department VARCHAR(150) NOT NULL,employment_type ENUM('full_time','part_time','contract','internship') NOT NULL DEFAULT 'full_time',location VARCHAR(180) NOT NULL,vacancy SMALLINT UNSIGNED DEFAULT 1,summary TEXT NOT NULL,responsibilities TEXT NULL,requirements TEXT NOT NULL,salary_range VARCHAR(100) NULL,application_deadline DATE NOT NULL,is_published BOOLEAN DEFAULT TRUE,created_by BIGINT UNSIGNED NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL,INDEX idx_job_public(is_published,application_deadline)
)ENGINE=InnoDB;
CREATE TABLE job_applications(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,application_number VARCHAR(30) NOT NULL UNIQUE,job_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NULL,full_name VARCHAR(150) NOT NULL,email VARCHAR(190) NOT NULL,phone VARCHAR(25) NOT NULL,address VARCHAR(300) NULL,education VARCHAR(300) NOT NULL,experience_years DECIMAL(4,1) DEFAULT 0,cover_letter TEXT NULL,resume_path VARCHAR(255) NOT NULL,status ENUM('submitted','reviewing','shortlisted','interview','selected','rejected') DEFAULT 'submitted',admin_note TEXT NULL,applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(job_id) REFERENCES career_jobs(id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL,INDEX idx_job_application(job_id,status)
)ENGINE=InnoDB;
CREATE TABLE campus_ambassador_programs(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(180) NOT NULL,overview TEXT NOT NULL,benefits TEXT NOT NULL,eligibility TEXT NOT NULL,responsibilities TEXT NOT NULL,application_deadline DATE NOT NULL,is_active BOOLEAN DEFAULT TRUE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB;
CREATE TABLE campus_ambassador_applications(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,application_number VARCHAR(30) NOT NULL UNIQUE,program_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NULL,full_name VARCHAR(150) NOT NULL,email VARCHAR(190) NOT NULL,phone VARCHAR(25) NOT NULL,institution VARCHAR(200) NOT NULL,student_id VARCHAR(80) NULL,department VARCHAR(150) NOT NULL,study_year VARCHAR(50) NOT NULL,facebook_url VARCHAR(255) NULL,why_join TEXT NOT NULL,experience TEXT NULL,status ENUM('submitted','reviewing','approved','rejected') DEFAULT 'submitted',admin_note TEXT NULL,applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(program_id) REFERENCES campus_ambassador_programs(id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL,INDEX idx_ambassador_status(status)
)ENGINE=InnoDB;
CREATE TABLE affiliates(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL UNIQUE,affiliate_code VARCHAR(20) NOT NULL UNIQUE,organization_name VARCHAR(180) NULL,promotion_method VARCHAR(200) NOT NULL,payment_method VARCHAR(80) NULL,payment_account VARCHAR(150) NULL,commission_rate DECIMAL(5,2) NOT NULL DEFAULT 5.00,status ENUM('pending','active','suspended','rejected') DEFAULT 'pending',approved_by BIGINT UNSIGNED NULL,approved_at TIMESTAMP NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(approved_by) REFERENCES users(id) ON DELETE SET NULL
)ENGINE=InnoDB;
CREATE TABLE affiliate_referrals(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,affiliate_id BIGINT UNSIGNED NOT NULL,referral_code VARCHAR(20) NOT NULL,visitor_token CHAR(64) NULL,landing_page VARCHAR(255) NULL,referred_user_id BIGINT UNSIGNED NULL,conversion_type VARCHAR(80) NULL,conversion_reference_id BIGINT UNSIGNED NULL,commission_amount DECIMAL(10,2) DEFAULT 0,status ENUM('visited','converted','approved','cancelled') DEFAULT 'visited',referred_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,converted_at TIMESTAMP NULL,FOREIGN KEY(affiliate_id) REFERENCES affiliates(id) ON DELETE CASCADE,FOREIGN KEY(referred_user_id) REFERENCES users(id) ON DELETE SET NULL,INDEX idx_referral_affiliate(affiliate_id,status),INDEX idx_referral_code(referral_code)
)ENGINE=InnoDB;
CREATE TABLE affiliate_commissions(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,affiliate_id BIGINT UNSIGNED NOT NULL,referral_id BIGINT UNSIGNED NULL,description VARCHAR(255) NOT NULL,amount DECIMAL(10,2) NOT NULL,status ENUM('pending','approved','paid','cancelled') DEFAULT 'pending',approved_by BIGINT UNSIGNED NULL,approved_at TIMESTAMP NULL,paid_at TIMESTAMP NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(affiliate_id) REFERENCES affiliates(id) ON DELETE CASCADE,FOREIGN KEY(referral_id) REFERENCES affiliate_referrals(id) ON DELETE SET NULL,FOREIGN KEY(approved_by) REFERENCES users(id) ON DELETE SET NULL,INDEX idx_commission_affiliate(affiliate_id,status)
)ENGINE=InnoDB;

INSERT IGNORE INTO permissions(name,label)VALUES('careers.manage','Manage careers and job applications'),('ambassadors.manage','Manage campus ambassador program'),('affiliates.manage','Manage affiliates and commissions');
INSERT IGNORE INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.name='admin' AND p.name IN('careers.manage','ambassadors.manage','affiliates.manage');
INSERT INTO career_jobs(title,slug,department,employment_type,location,vacancy,summary,responsibilities,requirements,salary_range,application_deadline,is_published) VALUES('Medical Officer','medical-officer','Emergency Medicine','full_time','Siddhirganj, Narayanganj',2,'Join our emergency care team and provide safe, compassionate patient care.','Assess patients, document care, coordinate with consultants and support emergency response.','MBBS with valid BMDC registration; emergency-care experience preferred.','As per hospital policy',DATE_ADD(CURDATE(),INTERVAL 45 DAY),1);
INSERT INTO campus_ambassador_programs(title,overview,benefits,eligibility,responsibilities,application_deadline,is_active) VALUES('Advance Care Campus Ambassador Program','Represent Advance Care Specialized Hospital in your educational institution and promote verified health-awareness initiatives.','Certificate, training, networking, recognition and performance-based opportunities.','Currently enrolled university or college student with good communication skills.','Share approved campaigns, coordinate awareness activities and submit activity reports.',DATE_ADD(CURDATE(),INTERVAL 60 DAY),1);
