USE advance_care_hospital;

CREATE TABLE IF NOT EXISTS pages(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,slug VARCHAR(100) UNIQUE NOT NULL,title VARCHAR(180) NOT NULL,subtitle VARCHAR(255),body LONGTEXT NOT NULL,image VARCHAR(255),is_published BOOLEAN DEFAULT TRUE,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS leaders(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,designation VARCHAR(150) NOT NULL,category ENUM('chairman','managing_director','board','administration') NOT NULL,qualifications VARCHAR(255),message LONGTEXT,photo VARCHAR(255),display_order INT DEFAULT 0,is_active BOOLEAN DEFAULT TRUE)ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS departments(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) UNIQUE NOT NULL,slug VARCHAR(140) UNIQUE NOT NULL,icon VARCHAR(50),short_description VARCHAR(300),description LONGTEXT,services TEXT,facilities TEXT,image VARCHAR(255),is_featured BOOLEAN DEFAULT FALSE,is_active BOOLEAN DEFAULT TRUE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS doctors(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,slug VARCHAR(140) UNIQUE NOT NULL,designation VARCHAR(150),specialization VARCHAR(150) NOT NULL,qualifications VARCHAR(255),experience_years INT UNSIGNED DEFAULT 0,consultation_fee DECIMAL(10,2) DEFAULT 0,bio TEXT,photo VARCHAR(255),available_days VARCHAR(150),available_time VARCHAR(100),is_featured BOOLEAN DEFAULT FALSE,is_active BOOLEAN DEFAULT TRUE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS doctor_departments(doctor_id BIGINT UNSIGNED NOT NULL,department_id BIGINT UNSIGNED NOT NULL,PRIMARY KEY(doctor_id,department_id),FOREIGN KEY(doctor_id)REFERENCES doctors(id)ON DELETE CASCADE,FOREIGN KEY(department_id)REFERENCES departments(id)ON DELETE CASCADE)ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS diagnostic_categories(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) UNIQUE NOT NULL,is_active BOOLEAN DEFAULT TRUE)ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS diagnostic_tests(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,category_id BIGINT UNSIGNED NOT NULL,name VARCHAR(160) UNIQUE NOT NULL,description TEXT,preparation TEXT,price DECIMAL(10,2) DEFAULT 0,report_time VARCHAR(100),is_active BOOLEAN DEFAULT TRUE,FOREIGN KEY(category_id)REFERENCES diagnostic_categories(id))ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS facilities(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(140) UNIQUE NOT NULL,slug VARCHAR(150) UNIQUE NOT NULL,icon VARCHAR(50),short_description VARCHAR(300),description TEXT,image VARCHAR(255),availability VARCHAR(100),contact VARCHAR(30),is_featured BOOLEAN DEFAULT FALSE,is_active BOOLEAN DEFAULT TRUE)ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS cabin_types(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) UNIQUE NOT NULL,description TEXT,daily_charge DECIMAL(10,2) NOT NULL,capacity INT UNSIGNED DEFAULT 1,amenities TEXT,image VARCHAR(255),availability ENUM('available','limited','unavailable') DEFAULT 'available',is_active BOOLEAN DEFAULT TRUE)ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS news(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(180) NOT NULL,slug VARCHAR(200) UNIQUE NOT NULL,category VARCHAR(100),excerpt VARCHAR(350),body LONGTEXT,image VARCHAR(255),published_at DATETIME,author VARCHAR(120),is_published BOOLEAN DEFAULT TRUE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS patient_video_reviews(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(180) NOT NULL,patient_name VARCHAR(120) DEFAULT 'Verified Patient',department_id BIGINT UNSIGNED NULL,platform ENUM('youtube','facebook') NOT NULL,video_url VARCHAR(500) NOT NULL,embed_url VARCHAR(500) NOT NULL,thumbnail VARCHAR(500),description TEXT,consent_recorded BOOLEAN DEFAULT FALSE,is_featured BOOLEAN DEFAULT FALSE,is_published BOOLEAN DEFAULT FALSE,published_at DATETIME,FOREIGN KEY(department_id)REFERENCES departments(id)ON DELETE SET NULL)ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS contact_messages(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(190),phone VARCHAR(20) NOT NULL,subject VARCHAR(180) NOT NULL,message TEXT NOT NULL,status ENUM('new','read','resolved') DEFAULT 'new',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS feedback(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120),phone VARCHAR(20),service VARCHAR(120),rating TINYINT UNSIGNED NOT NULL,comments TEXT NOT NULL,is_anonymous BOOLEAN DEFAULT FALSE,status ENUM('pending','published','archived') DEFAULT 'pending',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,CHECK(rating BETWEEN 1 AND 5))ENGINE=InnoDB;

INSERT IGNORE INTO pages(slug,title,subtitle,body)VALUES
('about','About Advance Care Specialized Hospital','Compassionate healthcare supported by modern technology.','Advance Care Specialized Hospital is committed to accessible, ethical and patient-centred healthcare. Our multidisciplinary teams work together to provide safe and coordinated services.\n\nMission: Deliver dependable specialist care with compassion and integrity.\n\nVision: Become a trusted digital-first healthcare institution in Bangladesh.\n\nCore values: Compassion, integrity, excellence, safety, innovation and accessibility.'),
('administration','Hospital Administration','Leadership focused on quality, safety and service.','Our administration coordinates clinical services, nursing, operations, patient support and continuous quality improvement.');
INSERT IGNORE INTO leaders(name,designation,category,message,display_order)VALUES
('Dr. A. Rahman','Chairman','chairman','Healthcare is built on trust. Our responsibility is to combine clinical excellence with compassion, safety and respect for every patient.',1),
('M. Karim','Managing Director','managing_director','We are investing in skilled people, modern systems and accessible services to create a better experience for patients and families.',1),
('Prof. S. Ahmed','Board Member','board','Clinical governance and patient safety.',1),('N. Islam','Board Member','board','Community health and institutional development.',2),
('Dr. F. Jahan','Medical Director','administration','Medical administration and quality assurance.',1),('R. Hossain','Head of Operations','administration','Hospital operations and patient services.',2);
INSERT IGNORE INTO departments(name,slug,icon,short_description,description,services,facilities,is_featured)VALUES
('Cardiology','cardiology','♥','Heart and cardiovascular care.','Specialist assessment and coordinated cardiovascular care.','Consultation, ECG, Echocardiography, Cardiac monitoring','CCU, Diagnostic support',1),
('Neurology','neurology','◉','Brain, spine and nervous-system care.','Evaluation and care for neurological conditions.','Neurology consultation, EEG guidance, Stroke follow-up','Imaging support, Rehabilitation referral',1),
('Orthopedics','orthopedics','◆','Bone, joint and mobility care.','Comprehensive orthopedic consultation and treatment planning.','Fracture care, Joint assessment, Sports injury consultation','Operation theatre, Physiotherapy',1),
('Gastroenterology','gastroenterology','●','Digestive-system specialist services.','Evaluation of digestive, liver and gastrointestinal concerns.','Consultation, Endoscopy guidance, Liver care','Diagnostics, Day care',1),
('Pediatrics','pediatrics','★','Compassionate healthcare for children.','Age-appropriate consultation and child health support.','General pediatrics, Growth monitoring, Newborn follow-up','NICU support, Child-friendly care',1),
('Gynecology','gynecology','✦','Women’s health and maternity services.','Respectful specialist services for women at every stage.','Consultation, Antenatal care, Maternity support','Operation theatre, NICU support',1);
INSERT IGNORE INTO doctors(name,slug,designation,specialization,qualifications,experience_years,consultation_fee,bio,available_days,available_time,is_featured)VALUES
('Dr. Mahmudul Hasan','dr-mahmudul-hasan','Consultant Cardiologist','Cardiology','MBBS, MD (Cardiology)',12,1200,'Experienced in cardiovascular assessment and patient-centred follow-up.','Saturday, Monday, Wednesday','5:00 PM–8:00 PM',1),
('Dr. Nusrat Jahan','dr-nusrat-jahan','Consultant Neurologist','Neurology','MBBS, MD (Neurology)',10,1200,'Provides neurological consultation with clear communication and coordinated care.','Sunday, Tuesday, Thursday','4:00 PM–7:00 PM',1),
('Dr. Saimul Karim','dr-saimul-karim','Orthopedic Surgeon','Orthopedics','MBBS, MS (Ortho)',14,1500,'Focuses on bone, joint and mobility-related care.','Saturday, Monday, Wednesday','6:00 PM–9:00 PM',1),
('Dr. Afroza Rahman','dr-afroza-rahman','Consultant Gynecologist','Gynecology','MBBS, MS (Gynae & Obs)',11,1300,'Offers respectful women’s health and maternity consultation.','Sunday, Tuesday, Thursday','5:00 PM–8:00 PM',1);
INSERT IGNORE INTO doctor_departments SELECT d.id,p.id FROM doctors d JOIN departments p ON p.name=d.specialization;
INSERT IGNORE INTO diagnostic_categories(name)VALUES('Pathology'),('Radiology'),('Cardiology Diagnostics');
INSERT IGNORE INTO diagnostic_tests(category_id,name,description,preparation,price,report_time)SELECT id,'Complete Blood Count (CBC)','Measures important blood-cell indicators.','No fasting is usually required.',600,'Same day' FROM diagnostic_categories WHERE name='Pathology';
INSERT IGNORE INTO diagnostic_tests(category_id,name,description,preparation,price,report_time)SELECT id,'Blood Glucose (Fasting)','Measures fasting blood glucose.','Fast for 8–10 hours; water may be allowed.',350,'Same day' FROM diagnostic_categories WHERE name='Pathology';
INSERT IGNORE INTO diagnostic_tests(category_id,name,description,preparation,price,report_time)SELECT id,'Chest X-Ray','Radiographic examination of the chest.','Remove metal accessories before the test.',900,'Within 24 hours' FROM diagnostic_categories WHERE name='Radiology';
INSERT IGNORE INTO diagnostic_tests(category_id,name,description,preparation,price,report_time)SELECT id,'Echocardiogram','Ultrasound assessment of heart structure and function.','Follow the laboratory instructions.',2500,'Within 24 hours' FROM diagnostic_categories WHERE name='Cardiology Diagnostics';
INSERT IGNORE INTO facilities(name,slug,icon,short_description,description,availability,contact,is_featured)VALUES
('Emergency Service','emergency','🚑','Coordinated urgent-care support.','Emergency service supported by trained clinical and support teams.','24/7','10678',1),('ICU','icu','✚','Critical-care monitoring and support.','Intensive care with continuous monitoring and clinical coordination.','24/7','10678',1),('Operation Theatre','operation-theatre','⚕','Modern surgical environment.','Safety-focused operating facilities and recovery support.','Scheduled and emergency','10678',1),('Pharmacy','pharmacy','▣','Hospital pharmacy service.','Convenient access to prescribed medicines and pharmacist support.','24/7','10678',1),('Ambulance','ambulance','🚑','Patient transport and emergency response.','Coordinated ambulance assistance subject to availability.','24/7','01713-106787',1),('Radiology','radiology','◉','Imaging and diagnostic support.','Imaging services with preparation guidance and reporting workflows.','Daily','10678',1);
INSERT IGNORE INTO cabin_types(name,description,daily_charge,capacity,amenities,availability)VALUES
('VIP Cabin','Private premium cabin designed for comfort and family support.',8500,1,'AC, attached washroom, television, attendant seating, refrigerator','available'),('Deluxe Cabin','Comfortable private cabin with essential amenities.',6000,1,'AC, attached washroom, television, attendant seating','limited'),('AC Cabin','Affordable air-conditioned private cabin.',4000,1,'AC, attached washroom, attendant chair','available'),('Non-AC Cabin','Essential private accommodation at an accessible charge.',2500,1,'Attached washroom, fan, attendant chair','available');
INSERT IGNORE INTO news(title,slug,category,excerpt,body,published_at,author)VALUES
('Free Medical Camp Announcement','free-medical-camp','Community Care','Specialist consultation will be available during the upcoming medical camp.','Advance Care Specialized Hospital is arranging a community medical camp. Please contact the hospital for verified schedule, specialist availability and registration information.',NOW(),'Hospital Communications'),('Expanded Diagnostic Service Hours','expanded-diagnostic-hours','Service Update','Selected diagnostic services are now available for extended hours.','Patients are requested to confirm preparation requirements and reporting times with the diagnostic desk before visiting.',NOW(),'Diagnostic Department');
