<?php
namespace App\Controllers;use App\Core\{Auth,Database,Request,Response,Session,View};use App\Models\{Admin,Hospital};
final class AdminController{
 private function allow(string$p):void{if(!Auth::can($p))Response::abort(403);}
 public function dashboard(Request$r):void{$this->allow('dashboard.view');View::render('admin/dashboard',['title'=>'Admin Dashboard','stats'=>Admin::dashboard()]);}
 public function module(Request$r):void{$key=(string)$r->input('module','doctors');$c=Admin::module($key);$this->allow($c['permission']);View::render('admin/module',['title'=>$c['title'],'module'=>$key,'config'=>$c,'rows'=>Admin::rows($key,trim((string)$r->input('q',''))),'q'=>(string)$r->input('q','')]);}
 public function edit(Request$r):void{$key=(string)$r->input('module');$c=Admin::module($key);$this->allow($c['permission']);$id=(int)$r->input('id');$row=$id?Admin::row($key,$id):[];View::render('admin/edit',['title'=>($id?'Edit ':'Add ').$c['title'],'module'=>$key,'config'=>$c,'row'=>$row,'options'=>$this->options($key),'error'=>'']);}
 public function save(Request$r):void{$key=(string)$r->input('module');$c=Admin::module($key);$this->allow($c['permission']);try{Admin::save($key,$r->all());Session::flash('success',$c['title'].' saved successfully.');redirect('admin/module?module='.$key);}catch(\Throwable$e){View::render('admin/edit',['title'=>'Edit '.$c['title'],'module'=>$key,'config'=>$c,'row'=>$r->all(),'options'=>$this->options($key),'error'=>$e->getMessage()]);}}
 public function delete(Request$r):void{$key=(string)$r->input('module');$c=Admin::module($key);$this->allow($c['permission']);try{Admin::delete($key,(int)$r->input('id'));Session::flash('success','Record deleted.');}catch(\Throwable$e){Session::flash('error','This record is in use and cannot be deleted. Deactivate it instead.');}redirect('admin/module?module='.$key);}
 private function options(string$key):array{return['category_id'=>Hospital::all('diagnostic_categories','is_active=1',[],'name'),'department_id'=>Hospital::all('departments','is_active=1',[],'name')];}
 public function schedules(Request$r):void{$this->allow('schedules.manage');View::render('admin/schedules',['title'=>'Doctor Schedules','schedules'=>Admin::schedules(),'doctors'=>Hospital::doctors(),'edit'=>(int)$r->input('id')]);}
 public function saveSchedule(Request$r):void{$this->allow('schedules.manage');try{Admin::saveSchedule($r->all());Session::flash('success','Doctor schedule and time slots saved.');}catch(\Throwable$e){Session::flash('error',$e->getMessage());}redirect('admin/schedules');}
 public function appointments(Request$r):void{$this->allow('appointments.manage');$status=(string)$r->input('status','');$date=(string)$r->input('date','');View::render('admin/appointments',['title'=>'Appointment Management','appointments'=>Admin::appointments($status,$date),'status'=>$status,'date'=>$date]);}
 public function appointmentStatus(Request$r):void{$this->allow('appointments.manage');try{Admin::updateAppointment((int)$r->input('id'),(string)$r->input('status'),trim((string)$r->input('note','Updated by administrator')));Session::flash('success','Appointment status updated and patient notified.');}catch(\Throwable$e){Session::flash('error',$e->getMessage());}redirect('admin/appointments');}
 public function patients(Request$r):void{$this->allow('patients.manage');View::render('admin/patients',['title'=>'Patient Management','patients'=>Admin::patients()]);}
 public function patientToggle(Request$r):void{$this->allow('patients.manage');Admin::togglePatient((int)$r->input('id'));Session::flash('success','Patient account status updated.');redirect('admin/patients');}
 public function feedback(Request$r):void{$this->allow('feedback.manage');$type=(string)$r->input('type','messages');View::render('admin/feedback',['title'=>'Contact and Feedback','type'=>$type,'rows'=>Admin::feedback($type)]);}
 public function feedbackStatus(Request$r):void{$this->allow('feedback.manage');$type=(string)$r->input('type');Admin::feedbackStatus($type,(int)$r->input('id'),(string)$r->input('status'));Session::flash('success','Status updated.');redirect('admin/feedback?type='.$type);}
 public function reports(Request$r):void{$this->allow('reports.view');View::render('admin/reports',['title'=>'Reports and Statistics','report'=>Admin::report()]);}
 public function roles(Request$r):void{$this->allow('roles.manage');View::render('admin/roles',['title'=>'Roles and Permissions','roles'=>Admin::roles(),'permissions'=>Admin::permissions()]);}
 public function saveRole(Request$r):void{$this->allow('roles.manage');Admin::saveRole((int)$r->input('role_id'),(array)($r->input('permissions',[])));Session::flash('success','Role permissions updated.');redirect('admin/roles');}
 public function createRole(Request$r):void{$this->allow('roles.manage');try{Admin::createRole(trim((string)$r->input('name')),trim((string)$r->input('label')));Session::flash('success','New role created.');}catch(\Throwable$e){Session::flash('error',$e->getMessage());}redirect('admin/roles');}
 public function audits(Request$r):void{$this->allow('audit.view');View::render('admin/audits',['title'=>'Audit Logs','audits'=>Admin::audits()]);}
}
