<?php
namespace App\Controllers;use App\Core\{Auth,Database,Request,Response,Session,View};use App\Models\{Admin,Business};
final class AdminBusinessController{
 private function allow(string$p):void{if(!Auth::can($p))Response::abort(403);}
 public function jobs(Request$r):void{$this->allow('careers.manage');$id=(int)$r->input('id');View::render('admin/business-jobs',['title'=>'Career Management','rows'=>Business::jobs(true),'editing'=>$id?Business::job($id):[]]);}
 public function saveJob(Request$r):void{$this->allow('careers.manage');$d=$r->all();foreach(['title','slug','department','location','summary','requirements','application_deadline']as$f)if(trim((string)($d[$f]??''))===''){Session::flash('error',ucwords(str_replace('_',' ',$f)).' is required.');redirect('admin/business-jobs');}$pdo=Database::connection();$id=(int)($d['id']??0);$v=[$d['title'],$d['slug'],$d['department'],$d['employment_type'],$d['location'],max(1,(int)$d['vacancy']),$d['summary'],$d['responsibilities']?:null,$d['requirements'],$d['salary_range']?:null,$d['application_deadline'],isset($d['is_published'])];if($id){$pdo->prepare('UPDATE career_jobs SET title=?,slug=?,department=?,employment_type=?,location=?,vacancy=?,summary=?,responsibilities=?,requirements=?,salary_range=?,application_deadline=?,is_published=? WHERE id=?')->execute([...$v,$id]);}else{$pdo->prepare('INSERT INTO career_jobs(title,slug,department,employment_type,location,vacancy,summary,responsibilities,requirements,salary_range,application_deadline,is_published,created_by)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([...$v,Auth::id()]);$id=(int)$pdo->lastInsertId();}Admin::audit(($d['id']??null)?'update':'create','career_jobs',$id);Session::flash('success','Career listing saved.');redirect('admin/business-jobs');}
 public function applications(Request$r):void{$type=(string)$r->input('type','jobs');if(!in_array($type,['jobs','ambassadors'],true))Response::abort(404);$this->allow($type==='jobs'?'careers.manage':'ambassadors.manage');View::render('admin/business-applications',['title'=>$type==='jobs'?'Job Applications':'Ambassador Applications','type'=>$type,'rows'=>Business::adminApplications($type)]);}
 public function applicationStatus(Request$r):void{$type=(string)$r->input('type');$this->allow($type==='jobs'?'careers.manage':'ambassadors.manage');Business::setApplicationStatus($type,(int)$r->input('id'),(string)$r->input('status'),trim((string)$r->input('note','')));Session::flash('success','Application updated.');redirect('admin/business-applications?type='.$type);}
 public function resume(Request$r):void{$this->allow('careers.manage');$s=Database::connection()->prepare('SELECT id,resume_path FROM job_applications WHERE id=?');$s->execute([(int)$r->input('id')]);$row=$s->fetch();if(!$row)Response::abort(404);$name=basename((string)$row['resume_path']);$file=BASE_PATH.'/storage/resumes/'.$name;if(!is_file($file))Response::abort(404);$ext=strtolower(pathinfo($name,PATHINFO_EXTENSION));$types=['pdf'=>'application/pdf','doc'=>'application/msword','docx'=>'application/vnd.openxmlformats-officedocument.wordprocessingml.document'];if(!isset($types[$ext]))Response::abort(404);header('Content-Type: '.$types[$ext]);header('Content-Disposition: attachment; filename="resume-'.$row['id'].'.'.$ext.'"');header('X-Content-Type-Options: nosniff');header('Content-Length: '.filesize($file));readfile($file);exit;}
 public function programs(Request$r):void{$this->allow('ambassadors.manage');$rows=Business::programs(true);View::render('admin/business-programs',['title'=>'Ambassador Programs','rows'=>$rows]);}
 public function saveProgram(Request$r):void{$this->allow('ambassadors.manage');$d=$r->all();foreach(['title','overview','benefits','eligibility','responsibilities','application_deadline']as$f)if(empty($d[$f])){Session::flash('error','Complete all program fields.');redirect('admin/business-programs');}$s=Database::connection()->prepare('INSERT INTO campus_ambassador_programs(title,overview,benefits,eligibility,responsibilities,application_deadline,is_active)VALUES(?,?,?,?,?,?,?)');$s->execute([$d['title'],$d['overview'],$d['benefits'],$d['eligibility'],$d['responsibilities'],$d['application_deadline'],isset($d['is_active'])]);Admin::audit('create','campus_ambassador_programs',(int)Database::connection()->lastInsertId());Session::flash('success','Ambassador program created.');redirect('admin/business-programs');}
 public function affiliates(Request$r):void{$this->allow('affiliates.manage');View::render('admin/business-affiliates',['title'=>'Affiliate Management','rows'=>Business::affiliates()]);}
 public function affiliateStatus(Request$r):void{$this->allow('affiliates.manage');Business::updateAffiliate($r->all());Session::flash('success','Affiliate updated.');redirect('admin/business-affiliates');}
 public function commission(Request$r):void{$this->allow('affiliates.manage');Business::addCommission($r->all());Session::flash('success','Commission recorded.');redirect('admin/business-affiliates');}
}
