<?php
namespace App\Controllers;use App\Core\{Auth,Request,Response,Session,Validator,View};use App\Models\{Appointment,Hospital};
final class AppointmentController{
 public function create(Request$r):void{$doctorId=(int)$r->input('doctor',0);$date=(string)$r->input('date','');View::render('appointments/book',['title'=>'Book Appointment','doctors'=>Hospital::doctors(),'selectedDoctor'=>$doctorId,'selectedDate'=>$date,'slots'=>($doctorId&&$date)?Appointment::availableSlots($doctorId,$date):[],'errors'=>[],'old'=>[]]);}
 public function store(Request$r):void{$d=$r->all();$v=new Validator();if(!$v->validate($d,['doctor_id'=>'required','appointment_date'=>'required','appointment_time'=>'required','reason'=>'required|min:5']))return$this->bookError($d,$v->errors());if($d['appointment_date']<date('Y-m-d'))return$this->bookError($d,['appointment_date'=>['Choose today or a future date.']]);try{$a=Appointment::create(Auth::id(),$d);Session::flash('success','Appointment request submitted successfully.');redirect('appointment?id='.$a['id']);}catch(\RuntimeException$e){$this->bookError($d,['appointment_time'=>[$e->getMessage()]]);}}
 private function bookError(array$d,array$errors):void{$doctor=(int)($d['doctor_id']??0);$date=(string)($d['appointment_date']??'');View::render('appointments/book',['title'=>'Book Appointment','doctors'=>Hospital::doctors(),'selectedDoctor'=>$doctor,'selectedDate'=>$date,'slots'=>($doctor&&$date)?Appointment::availableSlots($doctor,$date):[],'errors'=>$errors,'old'=>$d]);}
 public function show(Request$r):void{$a=Appointment::findOwned((int)$r->input('id'),Auth::id());if(!$a)Response::abort(404);View::render('appointments/show',['title'=>'Appointment Details','appointment'=>$a]);}
 public function index(Request$r):void{$status=(string)$r->input('status','');View::render('appointments/index',['title'=>'My Appointments','appointments'=>Appointment::forPatient(Auth::id(),$status?:null),'status'=>$status]);}
 public function cancel(Request$r):void{try{Appointment::cancel((int)$r->input('id'),Auth::id(),trim((string)$r->input('reason','Cancelled by patient')));Session::flash('success','Appointment cancelled.');}catch(\RuntimeException$e){Session::flash('error',$e->getMessage());}redirect('appointments');}
 public function rescheduleForm(Request$r):void{$a=Appointment::findOwned((int)$r->input('id'),Auth::id());if(!$a)Response::abort(404);$date=(string)$r->input('date',$a['appointment_date']);View::render('appointments/reschedule',['title'=>'Reschedule Appointment','appointment'=>$a,'selectedDate'=>$date,'slots'=>Appointment::availableSlots((int)$a['doctor_id'],$date),'errors'=>[]]);}
 public function reschedule(Request$r):void{$id=(int)$r->input('id');$a=Appointment::findOwned($id,Auth::id());if(!$a)Response::abort(404);$date=(string)$r->input('appointment_date','');$time=(string)$r->input('appointment_time','');try{$a=Appointment::reschedule($id,Auth::id(),$date,$time);Session::flash('success','Appointment rescheduled and returned to pending confirmation.');redirect('appointment?id='.$a['id']);}catch(\RuntimeException$e){View::render('appointments/reschedule',['title'=>'Reschedule Appointment','appointment'=>$a,'selectedDate'=>$date,'slots'=>Appointment::availableSlots((int)$a['doctor_id'],$date),'errors'=>['appointment_time'=>[$e->getMessage()]]]);}}
}

