<?php
namespace App\Controllers;use App\Core\{Auth,Request,Response,Session,Validator,View};use App\Models\Business;
final class BusinessController{
 public function careers(Request$r):void{View::render('business/careers',['title'=>'Careers','jobs'=>Business::jobs()]);}
 public function job(Request$r):void{$job=Business::job((int)$r->input('id'));if(!$job||!$job['is_published'])Response::abort(404);View::render('business/job',['title'=>$job['title'],'job'=>$job,'errors'=>[],'old'=>[]]);}
 public function applyJob(Request$r):void{$d=$r->all();$job=Business::job((int)$r->input('job_id'));if(!$job||!$job['is_published']||$job['application_deadline']<date('Y-m-d'))Response::abort(404);$v=new Validator();if(!$v->validate($d,['full_name'=>'required|min:2','email'=>'required|email','phone'=>'required|min:7','education'=>'required|min:3'])){View::render('business/job',['title'=>$job['title'],'job'=>$job,'errors'=>$v->errors(),'old'=>$d]);return;}try{$path=$this->resume();$number=Business::application('job',$d,$path);Session::flash('success','Application submitted. Reference: '.$number);redirect('careers');}catch(\Throwable$e){View::render('business/job',['title'=>$job['title'],'job'=>$job,'errors'=>['resume'=>[$e->getMessage()]],'old'=>$d]);}}
 private function resume():string{if(empty($_FILES['resume'])||$_FILES['resume']['error']!==UPLOAD_ERR_OK)throw new \RuntimeException('A résumé file is required.');$f=$_FILES['resume'];if($f['size']>5*1024*1024)throw new \RuntimeException('Résumé must be 5 MB or smaller.');$mime=(new \finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name']);$types=['application/pdf'=>'pdf','application/msword'=>'doc','application/vnd.openxmlformats-officedocument.wordprocessingml.document'=>'docx'];if(!isset($types[$mime]))throw new \RuntimeException('Upload only PDF, DOC or DOCX.');$dir=BASE_PATH.'/storage/resumes';if(!is_dir($dir)&&!mkdir($dir,0750,true))throw new \RuntimeException('Upload directory is unavailable.');$name=bin2hex(random_bytes(20)).'.'.$types[$mime];if(!move_uploaded_file($f['tmp_name'],$dir.'/'.$name))throw new \RuntimeException('Résumé upload failed.');return$name;}
 public function ambassadors(Request$r):void{View::render('business/ambassadors',['title'=>'Campus Ambassador Program','programs'=>Business::programs(),'errors'=>[],'old'=>[]]);}
 public function applyAmbassador(Request$r):void{$d=$r->all();$programs=Business::programs();$ids=array_map('intval',array_column($programs,'id'));if(!in_array((int)$r->input('program_id'),$ids,true))Response::abort(404);$v=new Validator();if(!$v->validate($d,['full_name'=>'required|min:2','email'=>'required|email','phone'=>'required|min:7','institution'=>'required|min:2','department'=>'required|min:2','study_year'=>'required','why_join'=>'required|min:20'])){View::render('business/ambassadors',['title'=>'Campus Ambassador Program','programs'=>$programs,'errors'=>$v->errors(),'old'=>$d]);return;}$number=Business::application('ambassador',$d);Session::flash('success','Campus Ambassador application submitted. Reference: '.$number);redirect('campus-ambassador');}
 public function affiliate(Request$r):void{$a=Business::affiliateForUser(Auth::id());View::render('business/affiliate-register',['title'=>'Affiliate Program','affiliate'=>$a,'errors'=>[]]);}
 public function registerAffiliate(Request$r):void{if(Business::affiliateForUser(Auth::id()))redirect('affiliate/dashboard');$d=$r->all();$v=new Validator();if(!$v->validate($d,['promotion_method'=>'required|min:10'])){View::render('business/affiliate-register',['title'=>'Affiliate Program','affiliate'=>null,'errors'=>$v->errors()]);return;}Business::registerAffiliate($d);Session::flash('success','Affiliate application received and awaiting approval.');redirect('affiliate/dashboard');}
 public function affiliateDashboard(Request$r):void{View::render('business/affiliate-dashboard',['title'=>'Affiliate Dashboard','affiliate'=>Business::affiliateDashboard(Auth::id())]);}
 public function referral(Request$r):void{$code=preg_replace('/[^A-Z0-9]/','',strtoupper((string)$r->input('ref','')));if($code)Business::track($code,(string)$r->input('to','/'));$to=(string)$r->input('to','');if($to===''||str_contains($to,'://')||str_starts_with($to,'//'))$to='';redirect(ltrim($to,'/'));}
}
