<?php
namespace App\Models;use App\Core\{Auth,Database};
final class Admin{
 public static function modules():array{return[
  'doctors'=>['table'=>'doctors','title'=>'Doctors','permission'=>'doctors.manage','fields'=>['name','slug','department_id','designation','specialization','qualifications','experience_years','consultation_fee','bio','available_days','available_time','is_featured','is_active'],'required'=>['name','slug','department_id','specialization'],'list'=>['name','specialization','experience_years','consultation_fee','is_active']],
  'departments'=>['table'=>'departments','title'=>'Departments','permission'=>'departments.manage','fields'=>['name','slug','icon','short_description','description','services','facilities','is_featured','is_active'],'required'=>['name','slug'],'list'=>['name','short_description','is_featured','is_active']],
  'diagnostics'=>['table'=>'diagnostic_tests','title'=>'Diagnostic Tests','permission'=>'diagnostics.manage','fields'=>['category_id','name','description','preparation','price','report_time','is_active'],'required'=>['category_id','name'],'list'=>['name','category_id','price','report_time','is_active']],
  'facilities'=>['table'=>'facilities','title'=>'Facilities','permission'=>'facilities.manage','fields'=>['name','slug','icon','short_description','description','availability','contact','is_featured','is_active'],'required'=>['name','slug'],'list'=>['name','availability','contact','is_active']],
  'cabins'=>['table'=>'cabin_types','title'=>'Cabins','permission'=>'cabins.manage','fields'=>['name','description','daily_charge','capacity','amenities','availability','is_active'],'required'=>['name','daily_charge'],'list'=>['name','daily_charge','capacity','availability','is_active']],
  'news'=>['table'=>'news','title'=>'News','permission'=>'news.manage','fields'=>['title','slug','category','excerpt','body','published_at','author','is_published'],'required'=>['title','slug'],'list'=>['title','category','published_at','is_published']],
  'pages'=>['table'=>'pages','title'=>'Page Content','permission'=>'news.manage','fields'=>['slug','title','subtitle','body','is_published'],'required'=>['slug','title','body'],'list'=>['title','slug','is_published','updated_at']],
  'leaders'=>['table'=>'leaders','title'=>'Leadership Content','permission'=>'news.manage','fields'=>['name','designation','category','qualifications','message','display_order','is_active'],'required'=>['name','designation','category'],'list'=>['name','designation','category','display_order','is_active']],
  'videos'=>['table'=>'patient_video_reviews','title'=>'Patient Videos','permission'=>'videos.manage','fields'=>['title','patient_name','department_id','platform','video_url','embed_url','description','consent_recorded','is_featured','is_published','published_at'],'required'=>['title','platform','video_url','embed_url'],'list'=>['title','patient_name','platform','consent_recorded','is_published']],
 ];}
 public static function module(string$key):array{$m=self::modules();if(!isset($m[$key]))throw new \InvalidArgumentException('Unknown admin module.');return$m[$key];}
 public static function rows(string$module,string$q=''):array{$c=self::module($module);$sql="SELECT * FROM {$c['table']}";$p=[];if($q){$field=$c['list'][0];$sql.=" WHERE {$field} LIKE ?";$p[]="%{$q}%";}$sql.=' ORDER BY id DESC LIMIT 200';$s=Database::connection()->prepare($sql);$s->execute($p);return$s->fetchAll();}
 public static function row(string$module,int$id):?array{$c=self::module($module);$s=Database::connection()->prepare("SELECT * FROM {$c['table']} WHERE id=?");$s->execute([$id]);$row=$s->fetch()?:null;if($row&&$module==='doctors'){$x=Database::connection()->prepare('SELECT department_id FROM doctor_departments WHERE doctor_id=? LIMIT 1');$x->execute([$id]);$row['department_id']=$x->fetchColumn()?:null;}return$row;}
 public static function save(string$module,array$d):int{$c=self::module($module);$data=[];$departmentId=null;foreach($c['fields']as$f){$value=(str_starts_with($f,'is_')||$f==='consent_recorded')?(isset($d[$f])?1:0):((($d[$f]??'')==='')?null:$d[$f]);if($f==='department_id'&&$module==='doctors'){$departmentId=$value;continue;}$data[$f]=$value;}foreach($c['required']as$f){$value=$f==='department_id'?$departmentId:($data[$f]??null);if(empty($value))throw new \RuntimeException(ucwords(str_replace('_',' ',$f)).' is required.');}if($module==='videos'){if(!empty($data['is_published'])&&empty($data['consent_recorded']))throw new \RuntimeException('Patient consent must be recorded before publishing.');$host=strtolower((string)parse_url((string)$data['embed_url'],PHP_URL_HOST));$allowed=$data['platform']==='youtube'?['youtube.com','www.youtube.com','youtube-nocookie.com','www.youtube-nocookie.com']:['facebook.com','www.facebook.com'];if(!in_array($host,$allowed,true))throw new \RuntimeException('Use an official '.$data['platform'].' embed URL.');}$id=(int)($d['id']??0);$pdo=Database::connection();$editing=$id>0;$pdo->beginTransaction();try{if($id){$set=implode(',',array_map(fn($f)=>"{$f}=?",array_keys($data)));$s=$pdo->prepare("UPDATE {$c['table']} SET {$set} WHERE id=?");$s->execute([...array_values($data),$id]);}else{$fields=implode(',',array_keys($data));$marks=implode(',',array_fill(0,count($data),'?'));$s=$pdo->prepare("INSERT INTO {$c['table']}({$fields})VALUES({$marks})");$s->execute(array_values($data));$id=(int)$pdo->lastInsertId();}if($module==='doctors'){$pdo->prepare('DELETE FROM doctor_departments WHERE doctor_id=?')->execute([$id]);$pdo->prepare('INSERT INTO doctor_departments(doctor_id,department_id)VALUES(?,?)')->execute([$id,$departmentId]);}self::audit($editing?'update':'create',$c['table'],$id,$data+['department_id'=>$departmentId]);$pdo->commit();return$id;}catch(\Throwable$e){$pdo->rollBack();throw$e;}}
 public static function delete(string$module,int$id):void{$c=self::module($module);$s=Database::connection()->prepare("DELETE FROM {$c['table']} WHERE id=?");$s->execute([$id]);self::audit('delete',$c['table'],$id);}
 public static function audit(string$action,string$entity,int$id,array$meta=[]):void{$s=Database::connection()->prepare('INSERT INTO audit_logs(user_id,action,entity_type,entity_id,metadata,ip_address)VALUES(?,?,?,?,?,?)');$s->execute([Auth::id(),$action,$entity,$id,json_encode($meta,JSON_UNESCAPED_UNICODE),$_SERVER['REMOTE_ADDR']??null]);}
 public static function dashboard():array{$pdo=Database::connection();$queries=['today_appointments'=>"SELECT COUNT(*) FROM appointments WHERE appointment_date=CURDATE()",'pending_appointments'=>"SELECT COUNT(*) FROM appointments WHERE status='pending'",'patients'=>"SELECT COUNT(DISTINCT u.id) FROM users u JOIN user_roles ur ON ur.user_id=u.id JOIN roles r ON r.id=ur.role_id WHERE r.name='patient'",'doctors'=>"SELECT COUNT(*) FROM doctors WHERE is_active=1",'unread_messages'=>"SELECT COUNT(*) FROM contact_messages WHERE status='new'",'pending_feedback'=>"SELECT COUNT(*) FROM feedback WHERE status='pending'"];$out=[];foreach($queries as$k=>$sql)$out[$k]=(int)$pdo->query($sql)->fetchColumn();$out['recent']=$pdo->query("SELECT a.id,a.appointment_number,a.appointment_date,a.appointment_time,a.status,u.name patient_name,d.name doctor_name FROM appointments a JOIN users u ON u.id=a.patient_id JOIN doctors d ON d.id=a.doctor_id ORDER BY a.created_at DESC LIMIT 8")->fetchAll();return$out;}
 public static function appointments(string$status='',string$date=''):array{$sql='SELECT a.*,u.name patient_name,u.phone,d.name doctor_name,dp.name department_name FROM appointments a JOIN users u ON u.id=a.patient_id JOIN doctors d ON d.id=a.doctor_id JOIN departments dp ON dp.id=a.department_id WHERE 1';$p=[];if($status){$sql.=' AND a.status=?';$p[]=$status;}if($date){$sql.=' AND a.appointment_date=?';$p[]=$date;}$sql.=' ORDER BY a.appointment_date DESC,a.appointment_time';$s=Database::connection()->prepare($sql);$s->execute($p);return$s->fetchAll();}
 public static function updateAppointment(int$id,string$status,string$note):void{$allowed=['pending','confirmed','completed','cancelled','no_show'];if(!in_array($status,$allowed,true))throw new \RuntimeException('Invalid appointment status.');$pdo=Database::connection();$pdo->beginTransaction();try{$s=$pdo->prepare('SELECT patient_id,status,appointment_number FROM appointments WHERE id=? FOR UPDATE');$s->execute([$id]);$a=$s->fetch();if(!$a)throw new \RuntimeException('Appointment not found.');$s=$pdo->prepare('UPDATE appointments SET status=? WHERE id=?');$s->execute([$status,$id]);$s=$pdo->prepare('INSERT INTO appointment_status_history(appointment_id,old_status,new_status,changed_by,note)VALUES(?,?,?,?,?)');$s->execute([$id,$a['status'],$status,Auth::id(),$note]);Patient::notify((int)$a['patient_id'],'appointment','Appointment '.ucfirst($status),'Appointment '.$a['appointment_number'].' is now '.$status.'.','appointment?id='.$id);self::audit('status_change','appointments',$id,['from'=>$a['status'],'to'=>$status,'note'=>$note]);$pdo->commit();}catch(\Throwable$e){$pdo->rollBack();throw$e;}}
 public static function patients():array{return Database::connection()->query("SELECT u.id,u.name,u.email,u.phone,u.is_active,u.created_at,COUNT(a.id) appointment_count FROM users u JOIN user_roles ur ON ur.user_id=u.id JOIN roles r ON r.id=ur.role_id AND r.name='patient' LEFT JOIN appointments a ON a.patient_id=u.id GROUP BY u.id ORDER BY u.created_at DESC")->fetchAll();}
 public static function togglePatient(int$id):void{$s=Database::connection()->prepare('UPDATE users SET is_active=NOT is_active WHERE id=?');$s->execute([$id]);self::audit('toggle_status','users',$id);}
 public static function feedback(string$type):array{$table=$type==='messages'?'contact_messages':'feedback';return Database::connection()->query("SELECT * FROM {$table} ORDER BY created_at DESC LIMIT 200")->fetchAll();}
 public static function feedbackStatus(string$type,int$id,string$status):void{$table=$type==='messages'?'contact_messages':'feedback';$allowed=$type==='messages'?['new','read','resolved']:['pending','published','archived'];if(!in_array($status,$allowed,true))throw new \RuntimeException('Invalid status.');$s=Database::connection()->prepare("UPDATE {$table} SET status=? WHERE id=?");$s->execute([$status,$id]);self::audit('status_change',$table,$id,['status'=>$status]);}
 public static function schedules():array{return Database::connection()->query('SELECT s.*,d.name doctor_name FROM doctor_schedules s JOIN doctors d ON d.id=s.doctor_id ORDER BY d.name,s.day_of_week,s.start_time')->fetchAll();}
 public static function saveSchedule(array$d):void{$id=(int)($d['id']??0);$editing=$id>0;if($id){$s=Database::connection()->prepare('UPDATE doctor_schedules SET doctor_id=?,day_of_week=?,start_time=?,end_time=?,slot_duration_minutes=?,room_number=?,is_active=? WHERE id=?');$s->execute([$d['doctor_id'],$d['day_of_week'],$d['start_time'],$d['end_time'],$d['slot_duration_minutes'],$d['room_number']?:null,isset($d['is_active']),$id]);}else{$s=Database::connection()->prepare('INSERT INTO doctor_schedules(doctor_id,day_of_week,start_time,end_time,slot_duration_minutes,room_number,is_active)VALUES(?,?,?,?,?,?,?)');$s->execute([$d['doctor_id'],$d['day_of_week'],$d['start_time'],$d['end_time'],$d['slot_duration_minutes'],$d['room_number']?:null,isset($d['is_active'])]);$id=(int)Database::connection()->lastInsertId();}self::rebuildSlots($id);self::audit($editing?'update':'create','doctor_schedules',$id,$d);}
 public static function rebuildSlots(int$scheduleId):void{$pdo=Database::connection();$s=$pdo->prepare('SELECT * FROM doctor_schedules WHERE id=?');$s->execute([$scheduleId]);$x=$s->fetch();if(!$x)return;$pdo->prepare('DELETE FROM doctor_time_slots WHERE schedule_id=?')->execute([$scheduleId]);$start=strtotime($x['start_time']);$end=strtotime($x['end_time']);$step=(int)$x['slot_duration_minutes']*60;$ins=$pdo->prepare('INSERT INTO doctor_time_slots(schedule_id,start_time,end_time)VALUES(?,?,?)');for($t=$start;$t+$step<=$end;$t+=$step)$ins->execute([$scheduleId,date('H:i:s',$t),date('H:i:s',$t+$step)]);}
 public static function report():array{$pdo=Database::connection();return['monthly'=>$pdo->query("SELECT DATE_FORMAT(created_at,'%Y-%m') month,COUNT(*) total,SUM(status='completed') completed,SUM(status='cancelled') cancelled FROM appointments GROUP BY month ORDER BY month DESC LIMIT 12")->fetchAll(),'departments'=>$pdo->query('SELECT d.name,COUNT(a.id) total FROM departments d LEFT JOIN appointments a ON a.department_id=d.id GROUP BY d.id ORDER BY total DESC')->fetchAll(),'doctors'=>$pdo->query('SELECT d.name,COUNT(a.id) total FROM doctors d LEFT JOIN appointments a ON a.doctor_id=d.id GROUP BY d.id ORDER BY total DESC')->fetchAll()];}
 public static function roles():array{$pdo=Database::connection();$roles=$pdo->query('SELECT * FROM roles ORDER BY name')->fetchAll();foreach($roles as&$r){$s=$pdo->prepare('SELECT permission_id FROM role_permissions WHERE role_id=?');$s->execute([$r['id']]);$r['permission_ids']=array_map('intval',array_column($s->fetchAll(),'permission_id'));}return$roles;}
 public static function permissions():array{return Database::connection()->query('SELECT * FROM permissions ORDER BY name')->fetchAll();}
 public static function saveRole(int$roleId,array$permissionIds):void{$pdo=Database::connection();$pdo->beginTransaction();try{$pdo->prepare('DELETE FROM role_permissions WHERE role_id=?')->execute([$roleId]);$s=$pdo->prepare('INSERT INTO role_permissions(role_id,permission_id)VALUES(?,?)');foreach($permissionIds as$p)$s->execute([$roleId,(int)$p]);self::audit('permissions_update','roles',$roleId,['permission_ids'=>$permissionIds]);$pdo->commit();}catch(\Throwable$e){$pdo->rollBack();throw$e;}}
 public static function createRole(string$name,string$label):void{if(!preg_match('/^[a-z][a-z0-9_]{2,49}$/',$name))throw new \RuntimeException('Role name must use lowercase letters, numbers or underscores.');$s=Database::connection()->prepare('INSERT INTO roles(name,label)VALUES(?,?)');$s->execute([$name,$label]);self::audit('create','roles',(int)Database::connection()->lastInsertId(),['name'=>$name,'label'=>$label]);}
 public static function audits():array{return Database::connection()->query('SELECT a.*,u.name user_name FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT 300')->fetchAll();}
}
