<?php
namespace App\Models;use App\Core\Database;use PDOException;
final class Appointment{
 public static function departmentForDoctor(int$doctorId):?int{$s=Database::connection()->prepare('SELECT department_id FROM doctor_departments WHERE doctor_id=? LIMIT 1');$s->execute([$doctorId]);$id=$s->fetchColumn();return$id?(int)$id:null;}
 public static function availableSlots(int$doctorId,string$date):array{if(!$date||strtotime($date)<strtotime(date('Y-m-d')))return[];$day=(int)date('N',strtotime($date));$s=Database::connection()->prepare("SELECT ts.start_time,ts.end_time,ds.room_number FROM doctor_time_slots ts JOIN doctor_schedules ds ON ds.id=ts.schedule_id WHERE ds.doctor_id=? AND ds.day_of_week=? AND ds.is_active=1 AND ts.is_active=1 AND ts.start_time NOT IN(SELECT appointment_time FROM appointments WHERE doctor_id=? AND appointment_date=? AND status IN('pending','confirmed')) ORDER BY ts.start_time");$s->execute([$doctorId,$day,$doctorId,$date]);return$s->fetchAll();}
 public static function validSlot(int$doctorId,string$date,string$time):bool{$day=(int)date('N',strtotime($date));$s=Database::connection()->prepare('SELECT COUNT(*) FROM doctor_time_slots ts JOIN doctor_schedules ds ON ds.id=ts.schedule_id WHERE ds.doctor_id=? AND ds.day_of_week=? AND ts.start_time=? AND ds.is_active=1 AND ts.is_active=1');$s->execute([$doctorId,$day,$time]);return(int)$s->fetchColumn()>0;}
 public static function create(int$patientId,array$d):array{$pdo=Database::connection();$department=self::departmentForDoctor((int)$d['doctor_id']);if(!$department)throw new \RuntimeException('The selected doctor has no assigned department.');if(!self::validSlot((int)$d['doctor_id'],$d['appointment_date'],$d['appointment_time']))throw new \RuntimeException('The selected time is not a valid doctor schedule.');$doctor=Hospital::one('doctors','id',(int)$d['doctor_id']);$number='ACSH-'.date('ymd').'-'.strtoupper(bin2hex(random_bytes(3)));$pdo->beginTransaction();try{$s=$pdo->prepare("INSERT INTO appointments(appointment_number,patient_id,doctor_id,department_id,appointment_date,appointment_time,reason,consultation_fee,status)VALUES(?,?,?,?,?,?,?,?, 'pending')");$s->execute([$number,$patientId,$d['doctor_id'],$department,$d['appointment_date'],$d['appointment_time'],$d['reason'],$doctor['consultation_fee']]);$id=(int)$pdo->lastInsertId();$s=$pdo->prepare("INSERT INTO appointment_status_history(appointment_id,new_status,changed_by,note)VALUES(?,'pending',?,'Appointment booked by patient')");$s->execute([$id,$patientId]);Patient::notify($patientId,'appointment','Appointment request received','Your appointment '.$number.' is pending confirmation.','appointment?id='.$id);$pdo->commit();return self::findOwned($id,$patientId);}catch(PDOException$e){$pdo->rollBack();if($e->getCode()==='23000')throw new \RuntimeException('This doctor and time slot has just been booked. Please choose another slot.');throw$e;}catch(\Throwable$e){$pdo->rollBack();throw$e;}}
 public static function findOwned(int$id,int$patientId):?array{$s=Database::connection()->prepare('SELECT a.*,d.name doctor_name,d.designation,d.qualifications,dp.name department_name FROM appointments a JOIN doctors d ON d.id=a.doctor_id JOIN departments dp ON dp.id=a.department_id WHERE a.id=? AND a.patient_id=?');$s->execute([$id,$patientId]);return$s->fetch()?:null;}
 public static function forPatient(int$patientId,?string$status=null):array{$sql='SELECT a.*,d.name doctor_name,d.specialization,dp.name department_name FROM appointments a JOIN doctors d ON d.id=a.doctor_id JOIN departments dp ON dp.id=a.department_id WHERE a.patient_id=?';$p=[$patientId];if($status&&in_array($status,['pending','confirmed','completed','cancelled','rescheduled','no_show'],true)){$sql.=' AND a.status=?';$p[]=$status;}$sql.=' ORDER BY a.appointment_date DESC,a.appointment_time DESC';$s=Database::connection()->prepare($sql);$s->execute($p);return$s->fetchAll();}
 public static function upcoming(int$patientId):?array{$s=Database::connection()->prepare("SELECT a.*,d.name doctor_name,dp.name department_name FROM appointments a JOIN doctors d ON d.id=a.doctor_id JOIN departments dp ON dp.id=a.department_id WHERE a.patient_id=? AND a.appointment_date>=CURDATE() AND a.status IN('pending','confirmed') ORDER BY a.appointment_date,a.appointment_time LIMIT 1");$s->execute([$patientId]);return$s->fetch()?:null;}
 public static function cancel(int$id,int$patientId,string$reason):void{$a=self::findOwned($id,$patientId);if(!$a||!in_array($a['status'],['pending','confirmed'],true))throw new \RuntimeException('This appointment cannot be cancelled.');if(strtotime($a['appointment_date'].' '.$a['appointment_time'])<=time())throw new \RuntimeException('Past appointments cannot be cancelled.');$pdo=Database::connection();$pdo->beginTransaction();try{$s=$pdo->prepare("UPDATE appointments SET status='cancelled',cancelled_at=NOW(),cancellation_reason=? WHERE id=? AND patient_id=?");$s->execute([$reason,$id,$patientId]);$s=$pdo->prepare("INSERT INTO appointment_status_history(appointment_id,old_status,new_status,changed_by,note)VALUES(?,?,'cancelled',?,?)");$s->execute([$id,$a['status'],$patientId,$reason]);Patient::notify($patientId,'appointment','Appointment cancelled','Appointment '.$a['appointment_number'].' has been cancelled.','appointments');$pdo->commit();}catch(\Throwable$e){$pdo->rollBack();throw$e;}}
 public static function reschedule(int$id,int$patientId,string$date,string$time):array{$a=self::findOwned($id,$patientId);if(!$a||!in_array($a['status'],['pending','confirmed'],true))throw new \RuntimeException('This appointment cannot be rescheduled.');if($date<date('Y-m-d')||!self::validSlot((int)$a['doctor_id'],$date,$time))throw new \RuntimeException('Choose a valid future schedule and time.');$pdo=Database::connection();$pdo->beginTransaction();try{$s=$pdo->prepare("UPDATE appointments SET appointment_date=?,appointment_time=?,status='pending' WHERE id=? AND patient_id=?");$s->execute([$date,$time,$id,$patientId]);$s=$pdo->prepare("INSERT INTO appointment_status_history(appointment_id,old_status,new_status,changed_by,note)VALUES(?,?,'pending',?,'Patient rescheduled appointment')");$s->execute([$id,$a['status'],$patientId]);Patient::notify($patientId,'appointment','Appointment rescheduled','Your new appointment date is '.date('d M Y',strtotime($date)).' at '.date('h:i A',strtotime($time)).'.','appointment?id='.$id);$pdo->commit();return self::findOwned($id,$patientId);}catch(PDOException$e){$pdo->rollBack();if($e->getCode()==='23000')throw new \RuntimeException('That time slot is no longer available.');throw$e;}}
}
