<?php
namespace App\Models;use App\Core\{Auth,Database};
final class Business{
 public static function jobs(bool$admin=false):array{$where=$admin?'1':"is_published=1 AND application_deadline>=CURDATE()";return Database::connection()->query("SELECT * FROM career_jobs WHERE {$where} ORDER BY application_deadline,id DESC")->fetchAll();}
 public static function job(int$id):?array{$s=Database::connection()->prepare('SELECT * FROM career_jobs WHERE id=?');$s->execute([$id]);return$s->fetch()?:null;}
 public static function application(string$type,array$d,string$resume=''):string{$pdo=Database::connection();$number=($type==='job'?'JOB':'CAM').date('ymd').strtoupper(bin2hex(random_bytes(3)));if($type==='job'){$s=$pdo->prepare('INSERT INTO job_applications(application_number,job_id,user_id,full_name,email,phone,address,education,experience_years,cover_letter,resume_path)VALUES(?,?,?,?,?,?,?,?,?,?,?)');$s->execute([$number,$d['job_id'],Auth::id(),$d['full_name'],$d['email'],$d['phone'],$d['address']?:null,$d['education'],(float)($d['experience_years']?:0),$d['cover_letter']?:null,$resume]);}else{$s=$pdo->prepare('INSERT INTO campus_ambassador_applications(application_number,program_id,user_id,full_name,email,phone,institution,student_id,department,study_year,facebook_url,why_join,experience)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)');$s->execute([$number,$d['program_id'],Auth::id(),$d['full_name'],$d['email'],$d['phone'],$d['institution'],$d['student_id']?:null,$d['department'],$d['study_year'],$d['facebook_url']?:null,$d['why_join'],$d['experience']?:null]);}return$number;}
 public static function programs(bool$admin=false):array{$where=$admin?'1':'is_active=1 AND application_deadline>=CURDATE()';return Database::connection()->query("SELECT * FROM campus_ambassador_programs WHERE {$where} ORDER BY application_deadline")->fetchAll();}
 public static function affiliateForUser(int$userId):?array{$s=Database::connection()->prepare('SELECT * FROM affiliates WHERE user_id=?');$s->execute([$userId]);return$s->fetch()?:null;}
 public static function registerAffiliate(array$d):void{$code='AC'.strtoupper(bin2hex(random_bytes(4)));$s=Database::connection()->prepare('INSERT INTO affiliates(user_id,affiliate_code,organization_name,promotion_method,payment_method,payment_account)VALUES(?,?,?,?,?,?)');$s->execute([Auth::id(),$code,$d['organization_name']?:null,$d['promotion_method'],$d['payment_method']?:null,$d['payment_account']?:null]);}
 public static function affiliateDashboard(int$userId):array{$a=self::affiliateForUser($userId);if(!$a)return[];$pdo=Database::connection();$s=$pdo->prepare('SELECT status,COUNT(*) total FROM affiliate_referrals WHERE affiliate_id=? GROUP BY status');$s->execute([$a['id']]);$a['referrals']=$s->fetchAll();$s=$pdo->prepare('SELECT * FROM affiliate_commissions WHERE affiliate_id=? ORDER BY created_at DESC LIMIT 100');$s->execute([$a['id']]);$a['commissions']=$s->fetchAll();$s=$pdo->prepare("SELECT COALESCE(SUM(amount),0) FROM affiliate_commissions WHERE affiliate_id=? AND status='paid'");$s->execute([$a['id']]);$a['paid_total']=$s->fetchColumn();$s=$pdo->prepare("SELECT COALESCE(SUM(amount),0) FROM affiliate_commissions WHERE affiliate_id=? AND status IN('pending','approved')");$s->execute([$a['id']]);$a['pending_total']=$s->fetchColumn();return$a;}
 public static function track(string$code,string$landing):void{$s=Database::connection()->prepare("SELECT id FROM affiliates WHERE affiliate_code=? AND status='active'");$s->execute([$code]);$id=$s->fetchColumn();if(!$id)return;$token=hash('sha256',session_id().'|'.$code.'|'.date('Y-m-d'));$s=Database::connection()->prepare('SELECT id FROM affiliate_referrals WHERE affiliate_id=? AND visitor_token=? AND referred_at>=CURDATE()');$s->execute([$id,$token]);if(!$s->fetchColumn())Database::connection()->prepare('INSERT INTO affiliate_referrals(affiliate_id,referral_code,visitor_token,landing_page)VALUES(?,?,?,?)')->execute([$id,$code,$token,mb_substr($landing,0,255)]);}
 public static function adminApplications(string$type):array{$table=$type==='jobs'?'job_applications':'campus_ambassador_applications';$join=$type==='jobs'?'JOIN career_jobs x ON x.id=a.job_id':'JOIN campus_ambassador_programs x ON x.id=a.program_id';return Database::connection()->query("SELECT a.*,x.title FROM {$table} a {$join} ORDER BY a.applied_at DESC")->fetchAll();}
 public static function setApplicationStatus(string$type,int$id,string$status,string$note):void{$map=['jobs'=>['table'=>'job_applications','allowed'=>['submitted','reviewing','shortlisted','interview','selected','rejected']],'ambassadors'=>['table'=>'campus_ambassador_applications','allowed'=>['submitted','reviewing','approved','rejected']]];if(!isset($map[$type])||!in_array($status,$map[$type]['allowed'],true))throw new \RuntimeException('Invalid application status.');$table=$map[$type]['table'];Database::connection()->prepare("UPDATE {$table} SET status=?,admin_note=? WHERE id=?")->execute([$status,$note?:null,$id]);Admin::audit('status_change',$table,$id,['status'=>$status]);}
 public static function affiliates():array{return Database::connection()->query('SELECT a.*,u.name,u.email,(SELECT COUNT(*) FROM affiliate_referrals r WHERE r.affiliate_id=a.id) referral_count,(SELECT COALESCE(SUM(c.amount),0) FROM affiliate_commissions c WHERE c.affiliate_id=a.id) commission_total FROM affiliates a JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC')->fetchAll();}
 public static function updateAffiliate(array$d):void{$allowed=['pending','active','suspended','rejected'];if(!in_array($d['status'],$allowed,true))throw new \RuntimeException('Invalid affiliate status.');$approved=$d['status']==='active';Database::connection()->prepare('UPDATE affiliates SET status=?,commission_rate=?,approved_by=?,approved_at=? WHERE id=?')->execute([$d['status'],max(0,min(100,(float)$d['commission_rate'])),$approved?Auth::id():null,$approved?date('Y-m-d H:i:s'):null,$d['id']]);Admin::audit('status_change','affiliates',(int)$d['id'],['status'=>$d['status']]);}
 public static function addCommission(array$d):void{$amount=(float)$d['amount'];if($amount<=0)throw new \RuntimeException('Commission must be greater than zero.');$s=Database::connection()->prepare('INSERT INTO affiliate_commissions(affiliate_id,description,amount,status,approved_by,approved_at,paid_at)VALUES(?,?,?,?,?,?,?)');$status=$d['status'];$s->execute([$d['affiliate_id'],$d['description'],$amount,$status,in_array($status,['approved','paid'],true)?Auth::id():null,in_array($status,['approved','paid'],true)?date('Y-m-d H:i:s'):null,$status==='paid'?date('Y-m-d H:i:s'):null]);Admin::audit('create','affiliate_commissions',(int)Database::connection()->lastInsertId(),['amount'=>$amount,'status'=>$status]);}
}
