<section class="hero"><div><span class="eyebrow">COMPASSIONATE CARE • ADVANCED MEDICINE</span><h1>Advanced Care.<br>Trusted Specialists.<br><em>Better Health.</em></h1><p>Expert healthcare, modern facilities and intelligent guidance—all in one trusted place.</p><a class="btn" href="#appointment">Book an Appointment</a> <a class="btn outline" href="<?=url('doctors')?>">Find a Doctor</a></div><div class="hero-art"><div>⚕<strong>Specialist care starts here</strong><small>Find the right department and doctor.</small></div></div></section>
<section class="appointment" id="appointment"><label>Department<select><option>Select Department</option><?php foreach($departments as$d):?><option><?=e($d['name'])?></option><?php endforeach;?></select></label><label>Doctor<select><option>Select Doctor</option><?php foreach($doctors as$d):?><option><?=e($d['name'])?></option><?php endforeach;?></select></label><label>Preferred Date<input type="date"></label><a class="btn" href="<?=url('doctors')?>">Search Availability</a></section>
<section class="section"><div class="heading"><span>HOW WE CAN HELP</span><h2>Care made easier</h2></div><div class="cards"><?php foreach([['🚑','Emergency','facilities'],['▣','Appointment','doctors'],['♙','Find Doctor','doctors'],['⚗','Diagnostics','diagnostics'],['✚','Facilities','facilities'],['▰','Cabins','cabins']]as$s):?><article><i><?=$s[0]?></i><h3><?=$s[1]?></h3><a href="<?=url($s[2])?>">Explore →</a></article><?php endforeach;?></div></section>
<section class="section about" id="about"><div class="hospital">ADVANCE CARE</div><div><span class="eyebrow">ABOUT US</span><h2>Compassionate care. Advanced technology. Better outcomes.</h2><p>Our secure digital platform connects patients with specialist doctors, departments and modern hospital services.</p><a class="text-link" href="<?=url('about')?>">Discover our hospital →</a><div class="stats"><b>120+<small>Specialists</small></b><b>20+<small>Departments</small></b><b>250+<small>Beds</small></b></div></div></section>
<section class="section soft"><div class="heading"><span>OUR DEPARTMENTS</span><h2>Specialized expertise</h2></div><div class="departments"><?php foreach($departments as$d):?><article><i><?=e($d['icon']?:'✚')?></i><h3><?=e($d['name'])?></h3><p><?=e($d['short_description'])?></p><a href="<?=url('department?id='.$d['id'])?>">View department →</a></article><?php endforeach;?></div></section>
<section class="section"><div class="heading"><span>OUR SPECIALISTS</span><h2>Meet featured doctors</h2></div><div class="doctor-grid"><?php foreach($doctors as$d):?><article class="doctor-card"><div class="doctor-photo">⚕</div><div><h3><?=e($d['name'])?></h3><p><?=e($d['designation'])?></p><b><?=e($d['specialization'])?></b><small><?=e($d['experience_years'])?> years experience</small><a class="btn small" href="<?=url('doctor?id='.$d['id'])?>">View Profile</a></div></article><?php endforeach;?></div></section>
<section class="section ai-panel"><div><span class="eyebrow">AI-POWERED CARE</span><h2>Meet your AI Healthcare Assistant</h2><p>Get hospital navigation and service information. This assistant does not provide medical diagnosis.</p><a class="btn purple" href="<?=url('ai-assistant')?>">Ask AI Assistant</a></div><div class="chat"><p>Hello! How can I help you today?</p><p class="mine">Help me find a department.</p><p>Tell me your main symptom and I’ll guide you safely.</p></div></section>
<section class="section"><div class="heading"><span>HEALTHCARE FACILITIES</span><h2>Support at every stage of care</h2></div><div class="facility-grid"><?php foreach($facilities as$f):?><article><i><?=e($f['icon'])?></i><h3><?=e($f['name'])?></h3><p><?=e($f['short_description'])?></p><b><?=e($f['availability'])?></b></article><?php endforeach;?></div></section>
<section class="section soft"><div class="heading"><span>PATIENT STORIES</span><h2>Real experiences, shared with consent</h2></div><?php if($videos):?><div class="videos"><?php foreach($videos as$v):?><article><div class="embed-wrap"><iframe loading="lazy" src="<?=e($v['embed_url'])?>" title="<?=e($v['title'])?>" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div><h3><?=e($v['title'])?></h3><p><?=e($v['patient_name'])?> • <?=e(ucfirst($v['platform']))?></p></article><?php endforeach;?></div><?php else:?><div class="empty">Approved YouTube and Facebook patient stories will appear here.</div><?php endif;?><p class="center"><a class="text-link" href="<?=url('patient-stories')?>">View all patient stories →</a></p></section>
<section class="section"><div class="heading"><span>LATEST UPDATES</span><h2>Hospital news</h2></div><div class="news-grid"><?php foreach($news as$n):?><article><span><?=e($n['category'])?></span><h3><?=e($n['title'])?></h3><p><?=e($n['excerpt'])?></p><a href="<?=url('article?id='.$n['id'])?>">Read more →</a></article><?php endforeach;?></div></section>
